<a href="https://colab.research.google.com/github/ObidulKadir/Python_Basic/blob/master/Generators_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



```
Generators():
generators is just like normal functions but its used ***yield*** insted of ***return***.

its very helpful because its memory consumpation operation.
```



In [9]:
def fib():
  first_num = 0
  second_num = 1
  while(True):
    next_value = first_num + second_num
    yield next_value
    first_num, second_num = second_num,next_value

g = fib()
print(g)

<generator object fib at 0x7fa7ab37b360>




```
SO output shows the generator expression object.So here if we want ta output from that object we have to use next()
```



In [13]:
for values in range(10):
  print(next(g))

21
34
55
89
144
233
377
610
987
1597




```
its starting the print from 21 .Interesting thing are happened here we are print some values from first so we range(10) that values its starting print after that .generators are create function state.so its very helpful. 
```



In [15]:
for i in range(20):
  print(next(g))

2584
4181
6765
10946
17711
28657
46368
75025
121393
196418
317811
514229
832040
1346269
2178309
3524578
5702887
9227465
14930352
24157817




---



```
here first value are 2584 which is sum of previous two 987
1597
```

